# Generated by Django 4.1.4 on 2022-12-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
    ]
