# Generated by Django 4.1.4 on 2023-01-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='application.service'),
        ),
    ]
